name: Trivy

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: "tvvlmj/${{ github.event.repository.name }}"

jobs:
  analyze:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ IMAGE_NAME }}:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "tvvlmj/mqtt-pulsar-forwarder:${{ github.sha }}"
          format: "sarif"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
